version: '3.8'
services:
dynamodb:
image: amazon/dynamodb-local
container_name: dynamodb-local
ports:
- "8000:8000"
command: -jar DynamoDBLocal.jar -sharedDb -inMemory


redis:
image: redis:7-alpine
container_name: redis-cache
ports:
- "6379:6379"